name: fork sync

on:
  schedule:
    - cron: '0 4 * * *' # at 04:00 every day
  workflow_dispatch:

jobs:
  update_fork:
    runs-on: ubuntu-latest
    name: rebase changes in fork on top of changes from upstream
    steps:
      - run: git clone --depth=50 --single-branch --branch=maint https://github.com/jvals/git.git
      - run: git remote add upstream https://github.com/git/git
        working-directory: git
      - run: git fetch upstream
        working-directory: git
      - run: git config --local user.email "$(git log --format='%ae' HEAD^!)"
        working-directory: git
      - run: git config --local user.name "$(git log --format='%an' HEAD^!)"
        working-directory: git
      - run: git rebase -Xtheirs upstream/maint
        working-directory: git
      - run: git push --force "https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/jvals/git" maint
        working-directory: git
